# -*- coding: utf-8 -*-
"""a1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16b0VnDWT8M1KvsLc6CQajAQ6FJZHwyCs

# Task 1
In task 1 the data was cleaned of data not needed. The data was structed in task 1 for easy access for task 2 as well.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("swedish_population_by_year_and_sex_1860-2022.csv")
#Start with filtering out data that is not intresting when it comes to the task at hand
df = df.drop("sex", axis=1) #Sex is not intresting in this scenario
df = df.drop("age", axis=1) #Age is intresting but due to the slicing operations later its not needed.
child = df.iloc[0:30]
child = pd.DataFrame(child[:].sum(), columns=["sum"])
labor = df.iloc[30:130]
labor = pd.DataFrame(labor[:].sum(), columns=["sum"])
elder = df.iloc[130:]
elder = pd.DataFrame(elder[:].sum(), columns=["sum"])

tot = pd.DataFrame(elder["sum"] + labor["sum"] + child["sum"])
index = list(elder.index) #index range of 1860 - 2022
index = [eval(x) for x in index]
axis_intervall = np.arange(1860, 2022, 10)

#Task 1 plot
plt.plot(index, (100 * ((elder["sum"] + child["sum"]) / labor["sum"]))) #Formula used in task 1
plt.show()

"""# Task 2"""

#Task 2 plot
plt.plot(index, elder/tot)
plt.plot(index, child/tot)
plt.plot(index, (child + elder)/tot)
plt.legend(["Elder", "Child", "Total dependent"])
plt.xlabel("Year")
plt.ylabel("Fraction of total population")
plt.xticks(axis_intervall)
plt.xticks(rotation=45, ha='right')
plt.show()

"""# Task 3

When looking at the data over the period from 1860 to 2022 some conclusion can be drawn. The Dependency Ratio seen in Fig. 1 had changed, reaching its top early in 1900, then decreased to mid 1900. Then finally grew again in the last decades. It is probable that the decrease around 1940 was mainly caused by low birth rates and migration because of the ending world war. Where the increase after 1960 is due to aging populations and cause of the historic event called "The Baby Boom".

Fig. 2 displays that the percentage of children went down rapidly post-1900, while the share of old people has been on a steady rise.

reflecting the shift to a longer life expectancy cause of advancements in technology and medicine and decrease of births which are trends developed countries share. Less young adults nowadays want kids or starting building families later in their careers.

The demographic of Sweden like the rest of the world industrialized countries shows that lower fertility rates, longer life expectancy, and aging populations.
"""